### ISSUE TITLE
T & C on Contribution Page not working

### ISSUE THREAD

**Issue by mwprojas** [veda-consulting-company/uk.co.vedaconsulting.gdpr#155]
My system:
WordPress 4.9.7
CiviCRM 5.3.2
GDPR Extension 2.6

New install of GDPR extension on my WordPress site. On the GDPR Dashboard, I have configured my GDPR settings, including adding a Data Policy document and a Terms & Conditions document for events and contribution pages, and that seems to work. Question #1: Is it possible to only show the Data Policy OR the Terms & Conditions, but not both?

Question #2: I only want the Terms & Conditions to appear on a particular contribution page. So I have not enabled the Terms & Conditions checkbox through the GDPR Dashboard. Instead, I navigate to Manage Contribution Pages, and go to the T & C tab. I am able to select where to place the checkbox, click save and don't get an error. But my selections are not actually saved, and the checkbox doesn't appear on my contribution form.

**Comment by Upperholme** [comment]
I'm seeing the same behaviour with 2.6 on a Drupal install.

**Comment by freeform-sg** [comment]
We are also looking to display the Data Policy but not the Terms & Conditions (because why would you need both?). 

Alternatively (or in addition to), we'd like to decide if acceptance of the Terms & Conditions is visible but optional (while Data Policy acceptance remains required). We'd like non-agreement to not prevent the user from completing a contribution, but limit their access to the system as a result.

The later can be achieved with a custom field outside of GDPR, but it would be nicer to have it integrated, but we certainly don't want 3 checkboxes, so disabling Terms & Conditions needs to be possible.

**Comment by tapashdatta** [comment]
PR welcome.
